# Generated by Django 3.2.9 on 2022-12-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookiesolver', '0002_rename_email_feedback_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='nike',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
