# Generated by Django 3.2.9 on 2022-12-26 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookiesolver', '0004_remove_feedback_nike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
