# Generated by Django 3.2.9 on 2023-03-09 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookiesolver', '0006_cookie_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookie_count',
            old_name='count',
            new_name='SEARCH_COUNT',
        ),
    ]
