# Generated by Django 3.2.9 on 2023-03-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookiesolver', '0007_rename_count_cookie_count_search_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie_count',
            name='SEARCH_COUNT',
            field=models.IntegerField(default=0),
        ),
    ]
